// Automatically generated by astro-icon
// e83b95c257aa5a99b97819fce0ac215995191cefe908492305296b5c7ac436bf

declare module 'virtual:astro-icon' {
	export type Icon = 
		| "ar"
		| "dk"
		| "email"
		| "gb"
		| "instagram"
		| "it"
		| "linkedin"
		| "menu"
		| "twitter"
		| "youtube";
}